image: node:15.5

stages:
  - deploy

production:
  stage: deploy
  before_script:
    - chmod +x ./setup_env.sh
    - ./setup_env.sh
    - npm install
    - npm install -g serverless
  script:
    - serverless deploy --stage prod --verbose
    - serverless deploy --stage dev --verbose
