#!/bin/bash

echo DOCUMENTDB_URL=$DOCUMENTDB_URL >> .env
echo DOCUMENTDB_URL_PROD=$DOCUMENTDB_URL_PROD >> .env
echo DOCUMENTDB_USER=$DOCUMENTDB_USER >> .env
echo DOCUMENTDB_USER_PROD=$DOCUMENTDB_USER_PROD >> .env
echo DOCUMENTDB_PASSWORD=$DOCUMENTDB_PASSWORD >> .env
echo DOCUMENTDB_PASSWORD_PROD=$DOCUMENTDB_PASSWORD_PROD >> .env
